import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import AuthProvider from '@/context/AuthProvider'
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { StateProvider } from '@/context/dashboard/statereducer'
import statereducer,{initialState } from '@/context/dashboard/Dashboardreducer'




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Second opinion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <AuthProvider>
        <StateProvider initialState={initialState || {}} reducer={statereducer}>
          {children}
          <Toaster />
        </StateProvider>
      </AuthProvider>
    </body>
  </html>
  );
}
